SELECT 
    UTS.COUNTRY,
    ROUND(AVG(UTS.TEMPO)) AS AVERAGE_TEMPO,
    ROUND(AVG(EXTRACT(YEAR FROM UTS.ALBUM_RELEASE_DATE)) - 0.5) AS AVERAGE_YEAR,
COUNT(DISTINCT UTS.NAME)
FROM 
    GROUP10.UNIVERSAL_TOP_SPOTIFY_SONGS UTS JOIN GROUP10.SPOTIFY_2023 S ON UTS.NAME = S.TRACK_NAME 
GROUP BY 
    UTS.COUNTRY;
