SELECT 
    UTS.NAME,
    MIN(UTS.DAILY_RANK) AS MIN_RANK
FROM 
    GROUP10.UNIVERSAL_TOP_SPOTIFY_SONGS UTS,
    GROUP10.SPOTIFY_2023 S
WHERE 
    UTS.NAME = S.TRACK_NAME
GROUP BY 
    UTS.NAME
HAVING 
    MIN(UTS.DAILY_RANK) <= 50;
