SELECT 
    ROW_NUMBER() OVER (ORDER BY U.ALBUM_RELEASE_DATE ASC) AS RN,
    U.NAME, 
    U.ARTISTS, 
    U.ALBUM_NAME, 
    U.ALBUM_RELEASE_DATE,
    U.COUNTRIES,
    S.STREAMS
FROM (
    SELECT 
        NAME, 
        ARTISTS, 
        ALBUM_NAME, 
        ALBUM_RELEASE_DATE,
        (SELECT LISTAGG(DISTINCT COUNTRY, ',') WITHIN GROUP (ORDER BY COUNTRY) 
         FROM GROUP10.UNIVERSAL_TOP_SPOTIFY_SONGS 
         WHERE NAME = UTS.NAME AND ARTISTS = UTS.ARTISTS) AS COUNTRIES,
        ROW_NUMBER() OVER (PARTITION BY NAME, ARTISTS ORDER BY ALBUM_RELEASE_DATE) AS RN_INNER
    FROM 
        GROUP10.UNIVERSAL_TOP_SPOTIFY_SONGS UTS
    WHERE 
        REGEXP_LIKE(NAME, '[一-鿿]')
) U
LEFT JOIN GROUP10.SPOTIFY_2023 S ON U.NAME = S.TRACK_NAME AND U.ARTISTS = S.ARTIST_NAMES
WHERE U.RN_INNER = 1
ORDER BY U.ALBUM_RELEASE_DATE ASC;
